### ISSUE TITLE
ML node

### ISSUE THREAD

**Issue by threewordphrase** [radoondas/flask-elastic-image-search#3]
Thank you for this excellent example, I have successfully used it to set up similarity search.

I am wondering how the pre-trained model in elasticsearch is utilized. I have an ML node in elastic cloud and I have imported the pre-trained model but I am unclear on if those things are necessary. I am already using sentence-transformers to extract image embeddings in my application - how is the model loaded into elasticsearch used?

If I can get rid of the ML node in elastic cloud, I can substantially reduce cost.

**Comment by radoondas** [comment]
Hello @threewordphrase !
Thanks for your feedback. I am glad to see that you were able to successfully deploy the example. 

> how is the model loaded into elasticsearch used?

When you create a vector (image embedding) from your image, store it in Elasticsearch in an index; then you have your vector database of image embeddings. 
When searching your images based on the generated vectors, you need a vector to search against them. In the case of this application, the "searching" vector is generated from the text query from the search bar. The vectorization of the text utilizes the NLP model loaded in Elasticsearch. This model can convert the search text to a vector and then use that vector as a "query term" for the vector database. 
So, the model in Elasticsearch is used to convert the text to a vector for your search against images. 
Having the model in Elasticsearch is very convenient because you do not need to utilize other infrastructure, and it uses Elasticsearch API for the `_inference`.
Note that the model to create image embeddings (from binary data to vector) and the model to generate vectors from your search text must be compatible (dimensions, type, learning content)

I hope this helps and if you want, you can read more on the topic in a miniseries I wrote. There are 3 parts.
[1](https://www.elastic.co/blog/5-technical-components-image-similarity-search), [2](https://www.elastic.co/blog/overview-image-similarity-search-in-elastic) and [3](https://www.elastic.co/blog/implement-image-similarity-search-elastic)

Feel free to let me know if you have more questions.

**Comment by radoondas** [comment]
I am closing this one for now. If you have more questions, feel free to reopen.
Thanks
